questions = [{
    "question": String.raw`Cлучайная величина \(\,\xi\,\)распределена равномерно \(\,U[0;\,1]\,\).Вероятность \(\,\operatorname{P}(0.5<\xi<0.7)\,\)равна`,
    "answers": {
        "A": String.raw`\(\,0.5\,\)`,
        "B": String.raw`\(\,0.2\,\)`,
        "C": String.raw`\(\,5/7\,\)`,
        "D": String.raw`\(\,\operatorname{P}\xi(0.7)-\operatorname{P}\xi(0.2)\,\)`,
        "E": String.raw`\(\,\int_{0}^{1}\frac{1}{\sqrt{2\pi}}\,e^{-t^2/2}\,dt\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Величина \(\,X\,\)распределена равномерно на отрезке \(\,[0,1]\,\),и \(\,\operatorname{E}(Y|X=x)=x^2\,\).Ожидание \(\,\operatorname{E}(Y)\,\)равно:`,
    "answers": {
        "A": String.raw`\(\,\frac{1}{2}\,\)`,
        "B": String.raw`\(\,\frac{3}{2}\,\)`,
        "C": String.raw`\(\,1\,\)`,
        "D": String.raw`\(\,0\,\)`,
        "E": String.raw`\(\,\frac{1}{3}\,\)`,
    },
    "true": "E",
    "explanation": "",
}, {
    "question": String.raw`Гена с \(\,6\,\)лет ждет письмо из школы волшебников.Время ожидания письма в годах экспоненциально распределено с параметром \(\,\lambda=\frac{1}{2}\,\).Вероятность того,что Гена получит письмо до \(\,18\,\)лет,если за \(\,10\,\)лет ожидания ему пока ничего не пришло,равна`,
    "answers": {
        "A": String.raw`\(\,1-e^{-6}\,\)`,
        "B": String.raw`\(\,1-e^{-1}\,\)`,
        "C": String.raw`\(\,1-e^{-2}\,\)`,
        "D": String.raw`\(\,6e^{-6}\,\)`,
        "E": String.raw`\(\,1-e^{-5}\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Количество скачиваний за день мобильного приложения распределено по Пуассону.В среднем приложение скачивают \(\,12\,\)раз за день.Вероятность того,что приложение будет скачено за день ровно \(\,5\,\)раз,равна`,
    "answers": {
        "A": String.raw`\(\,e^{-12}\frac{5^{12}}{12!}\,\)`,
        "B": String.raw`\(\,e^{-5}\,\)`,
        "C": String.raw`\(\,{e}^{-12}\frac{12^5}{5!}\,\)`,
        "D": String.raw`\(\,e^{-5}\frac{5^{12}}{12!}\,\)`,
        "E": String.raw`\(\,\frac{5}{12}\,\)`,
    },
    "true": "C",
    "explanation": "",
}, {
    "question": String.raw`Случайная величина \(\,X\,\)равномерно распределена на отрезке от \(\,-2\,\)до \(\,2\,\).Вероятность \(\,\operatorname{P}(X^2>0.64)\,\)равна`,
    "answers": {
        "A": String.raw`\(\,0.2\,\)`,
        "B": String.raw`\(\,0.8\,\)`,
        "C": String.raw`\(\,0.6\,\)`,
        "D": String.raw`\(\,0.1\,\)`,
        "E": String.raw`\(\,\frac{1}{2\sqrt{2}}\,\)`,
    },
    "true": "C",
    "explanation": "",
}, {
    "question": String.raw`В день Маша равновероятно съедает один,два или три кусочка тортика.Если Маша съела \(\,k\,\)кусочков,то она грустит с вероятностью \(\,1/(k+1)\,\).Безусловная вероятность того,что Маша грустит,равна`,
    "answers": {
        "A": String.raw`\(\,2/3\,\)`,
        "B": String.raw`\(\,0.5\,\)`,
        "C": String.raw`\(\,12/13\,\)`,
        "D": String.raw`\(\,13/36\,\)`,
        "E": String.raw`\(\,1/3\,\)`,
    },
    "true": "D",
    "explanation": "",
}, {
    "question": String.raw`Величина \(\,X\,\)имеет биномиальное распределение с параметрами \(\,n\,\)и \(\,p\,\).Дисперсия величины \(\,X\,\)максимальна при \(\,p\,\)равном`,
    "answers": {
        "A": String.raw`\(\,0.9\,\)`,
        "B": String.raw`\(\,0.5\,\)`,
        "C": String.raw`\(\,0.75\,\)`,
        "D": String.raw`\(\,0.2\,\)`,
        "E": String.raw`\(\,0.25\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`При каждом ударе по воротам Месси забивает гол с вероятностью \(\,0.9\,\),независимо от прошлых ударов.Вероятность того,что Месси забьет ровно три мяча за пять ударов,равна`,
    "answers": {
        "A": String.raw`\(\,C_{5}^{3}0.9^{3}0.1^2\,\)`,
        "B": String.raw`\(\,0.9^{4}0.1\,\)`,
        "C": String.raw`\(\,C_{5}^{2}0.1^30.9^5\,\)`,
        "D": String.raw`\(\,0.9^5\,\)`,
        "E": String.raw`\(\,\int_{3}^{5}\frac{1}{10}dx\,\)`,
    },
    "true": "A",
    "explanation": "",
}, {
    "question": String.raw`Джульетта загадывает случайное число \(\,X\,\)от \(\,1\,\)до \(\,5\,\).Единицу Джульетта загадывает с вероятностью \(\,0.5\,\),а остальные четыре числа---равновероятно.Энтропия \(\,H(X)\,\)в битах равна`,
    "answers": {
        "A": String.raw`\(\,1.75\,\)`,
        "B": String.raw`\(\,2\,\)`,
        "C": String.raw`\(\,\log_2 3\,\)`,
        "D": String.raw`\(\,\log 2 5+0.5\,\)`,
        "E": String.raw`\(\,\log_2 5-1\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Случайная величина \(\,X\,\)имеет равномерное распределение \(\,X\sim U[0,\alpha]\,\)и медиана \(\,X\,\)равна \(\,1\,\).Параметр \(\,\alpha\,\)равен`,
    "answers": {
        "A": String.raw`\(\,1.5\,\)`,
        "B": String.raw`\(\,2\,\)`,
        "C": String.raw`\(\,0.5\,\)`,
        "D": String.raw`\(\,0\,\)`,
        "E": String.raw`\(\,1\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Размер выплаты по страховому полису является неотрицательной величиной с математическим ожиданием 50,000 рублей и стандартным отклонением 10,000 рублей.Согласно неравенству Чебышева,вероятность того,что величина выплаты будет отличаться от своего математического ожидания не более чем на 30,000 рублей,не меньше`,
    "answers": {
        "A": String.raw`\(\,1/3\,\)`,
        "B": String.raw`\(\,2/3\,\)`,
        "C": String.raw`\(\,8/9\,\)`,
        "D": String.raw`\(\,1/2\,\)`,
        "E": String.raw`\(\,1/9\,\)`,
    },
    "true": "C",
    "explanation": "",
}, {
    "question": String.raw`Известно,что \(\,\operatorname{P}(A)=0.3\,\),\(\,\operatorname{P}(B|A)=0.7\,\).Вероятность того,что событие \(\,A\,\)произойдет,а событие \(\,B\,\)не произойдёт,равна`,
    "answers": {
        "A": String.raw`\(\,7/9\,\)`,
        "B": String.raw`\(\,0.4\,\)`,
        "C": String.raw`\(\,4/7\,\)`,
        "D": String.raw`\(\,0.09\,\)`,
        "E": String.raw`\(\,3/7\,\)`,
    },
    "true": "D",
    "explanation": "",
}, {
    "question": String.raw`Про случайные величины \(\,X,Y\,\)известно,что \(\,\operatorname{D}(X)=1\,\),\(\,\operatorname{D}(Y)=4\,\),\(\,\operatorname{Cov}(X,Y)=-1\,\).Корреляция \(\,\operatorname{Corr}(X,-2Y)\,\)равна`,
    "answers": {
        "A": String.raw`\(\,0.5\,\)`,
        "B": String.raw`\(\,-0.5\,\)`,
        "C": String.raw`\(\,1\,\)`,
        "D": String.raw`\(\,0\,\)`,
        "E": String.raw`\(\,-0.25\,\)`,
    },
    "true": "A",
    "explanation": "",
}, {
    "question": String.raw`Известно,что \(\,\operatorname{P}(A\cap B)=0.3\,\),\(\,\operatorname{P}(B|A)=0.6\,\).Вероятность того,что событие \(\,A\,\)произойдет,а событие \(\,B\,\)не произойдёт,равна`,
    "answers": {
        "A": String.raw`\(\,0.5\,\)`,
        "B": String.raw`\(\,2/3\,\)`,
        "C": String.raw`\(\,0.2\,\)`,
        "D": String.raw`\(\,1/3\,\)`,
        "E": String.raw`\(\,0.8\,\)`,
    },
    "true": "C",
    "explanation": "",
}, {
    "question": String.raw`Случайная величина \(\,X\,\)имеет функцию плотности \(\,f(x)=3x^2\,\)на отрезке \(\,[0;1]\,\).Ожидание \(\,\operatorname{E}(1/X)\,\)равно`,
    "answers": {
        "A": String.raw`\(\,2\,\)`,
        "B": String.raw`\(\,2/3\,\)`,
        "C": String.raw`\(\,3/2\,\)`,
        "D": String.raw`\(\,1/3\,\)`,
        "E": String.raw`\(\,1\,\)`,
    },
    "true": "C",
    "explanation": "",
}, {
    "question": String.raw`Мода экспоненциального распределения с параметром \(\,\lambda=5\,\)равна`,
    "answers": {
        "A": String.raw`\(\,e^{-5}\,\)`,
        "B": String.raw`\(\,5\,\)`,
        "C": String.raw`\(\,0.2\,\)`,
        "D": String.raw`\(\,0\,\)`,
        "E": String.raw`\(\,1-e^{-5}\,\)`,
    },
    "true": "D",
    "explanation": "",
}, {
    "question": String.raw`Величина \(\,X\,\)с равными вероятностями принимает только два значения,\(\,-1\,\)и \(\,1\,\),и \(\,\operatorname{E}(Y|X=x)=x-1\,\).Ожидание \(\,\operatorname{E}(Y)\,\)равно`,
    "answers": {
        "A": String.raw`\(\,x-1\,\)`,
        "B": String.raw`\(\,0\,\)`,
        "C": String.raw`\(\,1\,\)`,
        "D": String.raw`\(\,2\,\)`,
        "E": String.raw`\(\,-1\,\)`,
    },
    "true": "E",
    "explanation": "",
}, {
    "question": String.raw`Для энтропий пары случайных величин выполнено соотношение`,
    "answers": {
        "A": String.raw`\(\,H(X\cdot Y)/H(X)=H(Y|X)\,\)`,
        "B": String.raw`\(\,H(X)+H(Y)=H(X,Y)\,\)`,
        "C": String.raw`\(\,H(X)\cdot H(Y)=H(X,Y)\,\)`,
        "D": String.raw`\(\,H(Y|X)+H(X)=H(X,Y)\,\)`,
        "E": String.raw`\(\,H(Y|X)+H(X|Y)=H(X,Y)\,\)`,
    },
    "true": "D",
    "explanation": "",
}, {
    "question": String.raw`Ромео дарит Джульетте с вероятностью \(\,0.6\,\)розу,а с вероятностью \(\,0.4\,\)— шоколадку.Джульетта приходит в хорошее настроение от розы с вероятностью \(\,0.7\,\),а от шоколадки — с вероятностью \(\,0.8\,\).Сегодня Джульетта пришла в хорошее настроение от подарка Ромео.Вероятность того,что была подарена шоколадка,равна`,
    "answers": {
        "A": String.raw`\(\,21/37\,\)`,
        "B": String.raw`\(\,7/16\,\)`,
        "C": String.raw`\(\,16/37\,\)`,
        "D": String.raw`\(\,1/2\,\)`,
        "E": String.raw`\(\,16/21\,\)`,
    },
    "true": "C",
    "explanation": "",
}, {
    "question": String.raw`Если \(\,F_X(x)\,\)— функция распределения случайной величины \(\,X\,\),то для любых \(\,a\,\)и \(\,b\,\)`,
    "answers": {
        "A": String.raw`\(\,\operatorname{P}(X = a)=F_X(a)\,\)`,
        "B": String.raw`\(\,\operatorname{P}(X > a)=1 - F_X(a)\,\)`,
        "C": String.raw`\(\,\operatorname{P}(X < a)=1 - F_X(a)\,\)`,
        "D": String.raw`\(\,\operatorname{P}(X > a)=F_X (a)\,\)`,
        "E": String.raw`\(\,\operatorname{P}(a < X \le b) = F_X(a) - F_X(b) \,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Вася играет в компьютерную игру.Число выстрелов,необходимых,чтобы убить зомби,является случайной величиной с математическим ожиданием 2 и дисперсией 2.На уровне осталось 200 зомби,а у Васи — 420 патронов.Вероятность того,что Васе хватит патронов на весь уровень,примерно равна`,
    "answers": {
        "A": String.raw`\(\,1-\operatorname{P}\xi(2)\,\)`,
        "B": String.raw`\(\,1-\operatorname{P}\xi(1)\,\)`,
        "C": String.raw`\(\,\operatorname{P}\xi(1)\,\)`,
        "D": String.raw`\(\,\operatorname{P}\xi(2)\,\)`,
        "E": String.raw`\(\,0.5\,\)`,
    },
    "true": "C",
    "explanation": "",
}, {
    "question": String.raw`Величины \(\,X_1\,\),...,\(\,X_n\,\)независимы и одинаково распределены,\(\,\operatorname{E}(X)=1\,\),\(\,\operatorname{D}(X)=1\,\).По распределению к стандартной нормальной величине сходится последовательность`,
    "answers": {
        "A": String.raw`\(\,\sqrt{n}(1/\bar X-1)\,\)`,
        "B": String.raw`\(\,1/\bar X\,\)`,
        "C": String.raw`\(\,1/\bar X-1\,\)`,
        "D": String.raw`\(\,\bar X \sqrt{n}\,\)`,
        "E": String.raw`\(\,\bar X-1\,\)`,
    },
    "true": "A",
    "explanation": "",
}, {
    "question": String.raw`Маша берёт себе две карты из хорошо перемешанной колоды в 52 карты.Рассмотрим события \(\,A=\{\text{первая карта — туз}\}\,\),\(\,B=\{\text{вторая карта — дама}\}\,\)и \(\,C=\{\text{вторая карта — пики}\}\,\).Независимыми являются пары событий:`,
    "answers": {
        "A": String.raw`\(\,A\,\)и \(\,B\,\);\(\,B\,\)и \(\,C\,\)`,
        "B": String.raw`\(\,A\,\)и \(\,C\,\);\(\,B\,\)и \(\,C\,\)`,
        "C": String.raw`\(\,A\,\)и \(\,B\,\);\(\,A\,\)и \(\,C\,\)`,
        "D": String.raw`только \(\,A\,\)и \(\,C\,\)`,
        "E": String.raw`только \(\,A\,\)и \(\,B\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Величины \(\,X\,\)и \(\,Y\,\)одинаково распределены и равновероятно принимают только два значения,\(\,-1\,\)и \(\,1\,\),при этом \(\,\operatorname{P}(Y=1|X=1)=0.4\,\).Вероятность \(\,\operatorname{P}(Y=-1,X=1)\,\)равна`,
    "answers": {
        "A": String.raw`\(\,0.4\,\)`,
        "B": String.raw`\(\,0.3\,\)`,
        "C": String.raw`\(\,1\,\)`,
        "D": String.raw`\(\,0.5\,\)`,
        "E": String.raw`\(\,0.6\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Количество скачиваний за день мобильного приложения распределено по Пуассону.Дисперсия количества скачиваний равна \(\,10\,\).За скачивание приложения пользователи платят по \(\,5\,\)рублей.Ожидаемая выручка продавца за один день равна`,
    "answers": {
        "A": String.raw`\(\,350\,\)`,
        "B": String.raw`\(\,e^{-5}\frac{10^{5}}{5!}\,\)`,
        "C": String.raw`\(\,5\,\)`,
        "D": String.raw`\(\,50\,\)`,
        "E": String.raw`\(\,e^{-10}\frac{5^{10}}{10!}\,\)`,
    },
    "true": "D",
    "explanation": "",
}, {
    "question": String.raw`Совместная функция плотности пары случайных величин \(\,X\,\)и \(\,Y\,\)имеет вид \[f(x,y)=\begin{cases}c(2x+y),\;\text{если}x\in[0;2],y\in[0;2]\\ 0,\;\text{иначе}\end{cases}\]Константа \(\,c\,\)равна`,
    "answers": {
        "A": String.raw`\(\,1/6\,\)`,
        "B": String.raw`\(\,8\,\)`,
        "C": String.raw`\(\,1/8\,\)`,
        "D": String.raw`\(\,12\,\)`,
        "E": String.raw`\(\,1/12\,\)`,
    },
    "true": "E",
    "explanation": "",
}, {
    "question": String.raw`Величины \(\,X\,\)и \(\,Y\,\)независимы.Величина \(\,\frac{1}{X}\,\)распределена экспоненциально с \(\,\lambda=5\,\),величина \(\,Y\,\)распределена экспоненциально с \(\,\lambda=10\,\).Ожидание случайной величины \(\,Y/X\,\)равно`,
    "answers": {
        "A": String.raw`\(\,\frac{1}{50}\,\)`,
        "B": String.raw`\(\,2\,\)`,
        "C": String.raw`\(\,\frac{1}{2}\,\)`,
        "D": String.raw`\(\,1\,\)`,
        "E": String.raw`\(\,50\,\)`,
    },
    "true": "A",
    "explanation": "",
}, {
    "question": String.raw`Для дискретной случайной величины функция распределения`,
    "answers": {
        "A": String.raw`вырождена`,
        "B": String.raw`непрерывна`,
        "C": String.raw`строго возрастает`,
        "D": String.raw`имеет разрывы`,
        "E": String.raw`не определена`,
    },
    "true": "D",
    "explanation": "",
}, {
    "question": String.raw`Можно утверждать,что величины \(\,X\,\)и \(\,Y\,\)независимы,если`,
    "answers": {
        "A": String.raw`\(\,\operatorname{Cov}(Y,X)=0\,\)`,
        "B": String.raw`\(\,\operatorname{P}(X\le x,Y\le y)=\operatorname{P}(X\le x)\operatorname{P}(Y\le y)\,\)для любых \(\,x\,\)и \(\,y\,\)`,
        "C": String.raw`существуют такие \(\,x\,\)и \(\,y\,\),что;\(\,\operatorname{P}(X\le x,Y\le y)=\operatorname{P}(X\le x)\operatorname{P}(Y\le y)\,\)`,
        "D": String.raw`\(\,\operatorname{E}(YX)=\operatorname{E}(Y)\operatorname{E}(X)\,\)`,
        "E": String.raw`\(\,\operatorname{D}(Y+X)=\operatorname{D}(Y)+\operatorname{D}(X)\,\)`,
    },
    "true": "B",
    "explanation": "",
}, {
    "question": String.raw`Величины \(\,X\,\)и \(\,Y\,\)одинаково распределены и равновероятно принимают только два значения,\(\,-1\,\)и \(\,1\,\),при этом \(\,\operatorname{P}(Y=1|X=1)=0.5\,\).Ожидание \(\,\operatorname{E}(Y|X=1)\,\)равно`,
    "answers": {
        "A": String.raw`\(\,-0.5\,\)`,
        "B": String.raw`\(\,-1\,\)`,
        "C": String.raw`\(\,1\,\)`,
        "D": String.raw`\(\,0.5\,\)`,
        "E": String.raw`\(\,0\,\)`,
    },
    "true": "E",
    "explanation": "",
}, ];
init_question();
var result_array = new Array(questions.length);